@extends('frontend.layouts.master')

@section('title',' Privacy Policy')

@section('main-content')
		<section class="all-policy">
			<div class="container my-5">
				<x-policy-navbar-comp />
				
				<div class="privacy-policy">
					<h3 class="mt-4">Privacy Policies</h3>
					<div class="row">
						<div class=" col-10 mx-auto text-justify">
							<div class="content">
								<p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
								<p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of&nbsp;<span>grest.in website</span>.</p>
								<p><span>In using this website, you are deemed to have read and agreed to the following terms and conditions:</span></p>
								<p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and any or all Agreements: "Client", &ldquo;You&rdquo; and &ldquo;Your&rdquo; refers to you, the person accessing this website and accepting the Company&rsquo;s terms and conditions. "The Company", &ldquo;Ourselves&rdquo;, &ldquo;We&rdquo; and "Us", refers to our Company. &ldquo;Party&rdquo;, &ldquo;Parties&rdquo;, or &ldquo;Us&rdquo;, refers to both the Client and ourselves, or either the Client or ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner, whether by formal meetings of a fixed duration, or any other means, for the express purpose of meeting the Client&rsquo;s needs in respect of provision of the Company&rsquo;s stated services/products, in accordance with and subject to, prevailing Indian Law. Any use of the above terminology or other words in the singular, plural, capitalisation and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p><br>
								<h5>Privacy Statement</h5>
								<p>We are committed to protecting your privacy. Authorized employees within the company on a need to know basis only use any information collected from individual customers. We constantly review our systems and data to ensure the best possible service to our customers. Parliament has created specific offences for unauthorised actions against computer systems and data. We will investigate any such actions with a view to prosecuting and/or taking civil proceedings to recover damages against those responsible.</p>
								<br><h5>Confidentiality</h5>
								<p>Any information concerning the Customers/Client and their respective Customers/ Client Records may be passed to third parties. However, Client records are regarded as confidential and therefore will not be divulged to any third party, other than our manufacturer/supplier(s) and if legally required to do so to the appropriate authorities. Clients have the right to request sight of, and copies of any and all Client Records we keep, on the proviso that we are given reasonable notice of such a request. Clients are requested to retain copies of any literature issued in relation to the provision of our services. Where appropriate, we shall issue Client&rsquo;s with appropriate written information, handouts or copies of records as part of an agreed contract, for the benefit of both parties.</p>
								<p><span>We will not sell, share, or rent your personal information to any third party or use your e-mail address for unsolicited mail. Any emails sent by this Company will only be in connection with the provision of agreed services and products.</span></p>
								<br><h5>Disclaimer</h5>
								<h6>Exclusions and Limitations</h6>
								<p>The information on this web site is provided on an "as is" basis. To the fullest extent permitted by law, this Company:</p>
								<ul>
								<li>Excludes all representations and warranties relating to this website and its contents or which is or may be provided by any affiliates or any other third party, including in relation to any inaccuracies or omissions in this website and/or the Company&rsquo;s literature; and</li>
								<li>excludes all liability for damages arising out of or in connection with your use of this website. This includes, without limitation, direct loss, loss of business or profits (whether or not the loss of such profits was foreseeable, arose in the normal course of things or you have advised this Company of the possibility of such potential loss), damage caused to your computer, computer software, systems and programs and the data thereon or any other direct or indirect, consequential and incidental damages.</li>
								</ul>
								<p><br /><span>This Company does not however exclude liability for death or personal injury caused by its negligence. The above exclusions and limitations apply only to the extent permitted by law. None of your statutory rights as a consumer are affected.</span></p>
								<p>&nbsp;</p>
								<br><h5>User Obligations</h5>
								<p>You agree not to access (or attempt to access) the Website and the materials or Services by any means other than through the interface that is provided by us. You shall not use any deep-link, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the website or content, or in any way reproduce or circumvent the navigational structure or presentation of the Website, materials or any Content, to obtain or attempt to obtain any materials, documents or information through any means not specifically made available through the Website.</p>
								<p>You agree that you are solely responsible to us and to any third party for any breach of your obligations under the Terms of Use and for the consequences (including any loss or damage which we or our affiliates or our vendors may suffer) for any such breach.</p>
								<h6>Termination of Agreement and Refund Policy</h6>
								<p>Both the Client and ourselves have the right to terminate any Services Agreement for any reason, including the ending of services that are already underway. No refunds shall be offered, where a Service is deemed to have begun and is, for all intents and purposes, underway. Any monies that have been paid to us which constitute payment in respect of the provision of unused Services, shall be refunded.</p>
								<br><h5>Availability</h5>
								<p>Unless otherwise stated, the services featured on this website are only available within India, or in relation to postings from India. All advertising is intended solely for the Indian market. You are solely responsible for evaluating the fitness for a particular purpose of any downloads, programs and text available through this site. Redistribution or republication of any part of this site or its content is prohibited, including such by framing or other similar or any other means, without the express written consent of the Company. The Company does not warrant that the service from this site will be uninterrupted, timely or error free, although it is provided to the best ability. By using this service you thereby indemnify this Company, its employees, agents and affiliates against any loss or damage, in whatever manner, howsoever caused.</p>
								<br><h6>Log Files</h6>
								<p>We use IP addresses to analyse trends, administer the site, track user&rsquo;s movement, and gather broad demographic information for aggregate use. IP addresses are not linked to personally identifiable information. Additionally, for systems administration, detecting usage patterns and troubleshooting purposes, our web servers automatically log standard access information including browser type, access times/open mail, URL requested, and referral URL. This information is not shared with third parties and is used only within this Company on a need-to-know basis. Any individually identifiable information related to this data will never be used in any way different to that stated above without your explicit permission.</p>
								<br><h6>Applicable Law</h6>
								<p>Terms of Use shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be Gurgaon.</p>
								<br><h6>Links to this website</h6>
								<p>You may not create a link to any page of this website without our prior written consent. If you do create a link to a page of this website you do so at your own risk and the exclusions and limitations set out above will apply to your use of this website by linking to it.</p>
								<br><h6>Links from this website</h6>
								<p>We do not monitor or review the content of other party&rsquo;s websites which are linked to from this website. Opinions expressed or material appearing on such websites are not necessarily shared or endorsed by us and should not be regarded as the publisher of such opinions or material. Please be aware that we are not responsible for the privacy practices, or content, of these sites. We encourage our users to be aware when they leave our site &amp; to read the privacy statements of these sites. You should evaluate the security and trustworthiness of any other site connected to this site or accessed through this site yourself, before disclosing any personal information to them. This Company will not accept any responsibility for any loss or damage in whatever manner, howsoever caused, resulting from your disclosure to third parties of personal information.</p>
								<br><h6>Copyright Notice/Intellectual Property Rights</h6>
								<p>Copyright and other relevant intellectual property rights exists on all text relating to the Company&rsquo;s services and the full content of this website.</p>
								<p>This Company&rsquo;s logo is a registered trademark of this Company in India. The brand names and specific services of this Company featured on this web site are trade marked</p>
								<p>The Website and the processes, and their selection and arrangement, including but not limited to all text, graphics, user interfaces, visual interfaces, and computer code (collectively, the "Content") on the website is owned and controlled by us and the design, structure, selection, coordination, expression, look and feel and arrangement of such Content is protected by copyright, patent and trademark laws, and various other intellectual property rights.<br />Except as expressly provided herein, You acknowledge and agree that You shall not copy, republish, post, display, translate, transmit, reproduce or distribute any Content through any medium without obtaining the necessary authorization from Radical Aftermarket Services Pvt Ltd or thirty party owner of such Content.</p>
								<br><h6>Communication</h6>
								<p>We have several different e-mail addresses for different queries. These, &amp; other contact information, can be found on our Contact Us link on our website or via Company literature or via the Company&rsquo;s stated telephone, facsimile or mobile telephone numbers.</p>
								<p>This company is registered in Haryana, CIN U74999HR2018PTC076488 , registered office 7&amp;8, South City 1 Market, Opposite Mayom Hospital, Gurgaon, Haryana-122001</p>
								<br><h6>Force Majeure</h6>
								<p>Neither party shall be liable to the other for any failure to perform any obligation under any Agreement which is due to an event beyond the control of such party including but not limited to any Act of God, terrorism, war, Political insurgence, insurrection, riot, civil unrest, act of civil or military authority, uprising, earthquake, flood or any other natural or man-made eventuality outside of our control, which causes the termination of an agreement or contract entered into, nor which could have been reasonably foreseen. Any Party affected by such event shall forthwith inform the other Party of the same and shall use all reasonable endeavours to comply with the terms and conditions of any Agreement contained herein.</p>
								<br><h6>Waiver</h6>
								<p>Failure of either Party to insist upon strict performance of any provision of this or any Agreement or the failure of either Party to exercise any right or remedy to which it, he or they are entitled hereunder shall not constitute a waiver thereof and shall not cause a diminution of the obligations under this or any Agreement. No waiver of any of the provisions of this or any Agreement shall be effective unless it is expressly stated to be such and signed by both Parties.</p>
								<br><h6>General</h6>
								<p>The laws of India govern these terms and conditions. By accessing this website and using our services/buying our products you consent to these terms and conditions and to the exclusive jurisdiction of the Indian courts in all disputes arising out of such access. If any of these terms are deemed invalid or unenforceable for any reason (including, but not limited to the exclusions and limitations set out above), then the invalid or unenforceable provision will be severed from these terms and the remaining terms will continue to apply. Failure of the Company to enforce any of the provisions set out in these Terms and Conditions and any Agreement, or failure to exercise any option to terminate, shall not be construed as waiver of such provisions and shall not affect the validity of these Terms and Conditions or of any Agreement or any part thereof, or the right thereafter to enforce each and every provision. These Terms and Conditions shall not be amended, modified, varied or supplemented except in writing and signed by duly authorised representatives of the Company.</p>
								<br><h6>Notification of Changes</h6>
								<p>The Company reserves the right to change these conditions from time to time as it sees fit and your continued use of the site will signify your acceptance of any adjustment to these terms. If there are any changes to our privacy policy, we will announce that these changes have been made on our home page and on other key pages on our site. If there are any changes in how we use our site customers&rsquo; Personally Identifiable Information, notification by e-mail or postal mail will be made to those affected by this change. Any changes to our privacy policy will be posted on our web site 30 days prior to these changes taking place. You are therefore advised to re-read this statement on a regular basis</p>
								<p><span>These terms and conditions form part of the Agreement between the Client and ourselves. Your accessing of this website and/or undertaking of a booking or Agreement indicates your understanding, agreement to and acceptance, of the Disclaimer Notice and the full Terms and Conditions contained herein. Your statutory Consumer Rights are unaffected.<br />&copy; Radical Aftermarket Services Pvt Ltd 2020 All Rights Reserved.</span></p>
							</div>
						</div>
					</div>
				</div>

				{{-- <div class="terms">
					<h3 class="mt-4">Terms & Conditions</h3>
					<div class="row">
						<div class=" col-10 mx-auto text-justify">
							<div class="content">
								<p>By using it, you are agreeing to these Terms &amp; Conditions (defined below). Please read them carefully.
									Radical Aftermarket Services Pvt. Ltd. doing business as &ldquo;Grest&rdquo;</p>
								<p>&ldquo;Grest&rdquo; owns and operates the website, www.grest.in. The mobile touch versions, App on Play
									store and Apple App store and/or any site(s) we have now or in the future that reference these Terms &amp;
									Conditions (collectively, &ldquo;Grest&rdquo;), provides a marketplace and platform for consumers and
									organizations to sell or repair their used, old and other articles, and conduct varied transactions and
									activities, with third-party companies and other entities and persons (collectively, &ldquo;Third
									Parties&rdquo;). The Grest marketplace, platform, and related functionality, whether provided through the
									Site or through other means, are collectively referred to as the services (the &ldquo;Services&rdquo;).</p>
								<p>If you do not agree with any part of these Terms &amp; Conditions, you must not use the Site or Services.
									Your continued use of the Site or Services will constitute your acceptance of these Terms &amp; Conditions,
									as they may be modified by us from time to time, with or without notice to you. Please check this page
									regularly for updates to the Grest Terms &amp; Conditions.</p>
								<ol>
									<li><strong> Grest is a marketplace venue</strong>
										<p>Grest is a platform to allow users, subject to compliance with Grest&rsquo;s policies, to sell/repair
											certain goods. Grest may not be directly involved in the transaction between user(s) and third party
											professional(s), ensuing no control by reasons whatsoever in any aspect of your transactions with Third
											Parties, and the Third Parties are solely responsible to you for all aspects of your transactions with
											them.
										</p>
									</li>
								</ol>
			
								<ol start="2">
									<li><strong> Permitted Use and Compliance with Laws.</strong>
										<p>Grest authorizes you to access, view and use the Site content and software (collectively, the
											&ldquo;Manak
											Waste Management Pvt Ltd Property&rdquo;) solely to the extent necessary for you to use the Services.
											You
											may not remove any copyright, trademark or other proprietary notices that have been placed on the Grest
											Property. You may not engage in systematic retrieval of data or other content from the Grest Property.
											Except as expressly permitted by these Terms &amp; Conditions, any modification, reproduction,
											redistribution, republication, uploading, posting, transmitting, distributing or otherwise exploiting in
											any
											way the Grest Property, or any portion of the Grest Property, is strictly prohibited without the prior
											written permission of Manak Waste Management Pvt Ltd.</p>
										<p>You agree that you will comply with all applicable laws, regulations and ordinances relating to the
											Site
											and Services, the Grest Property or your use of them, and that in using the Site and Services you will
											not
											engage in any conduct that restricts or inhibits any other person from using or enjoying the Services.
										</p>
									</li>
								</ol>
			
								<ol start="3">
									<li><strong> Copyright and trademarks.</strong>
										<p>Except as otherwise indicated, all materials in the Site, including, but not limited to text, software,
											photos, video, graphics, music, sound, the Grest Logo, ScreenPro logo, ReGlobe Logo and other Grest,
											ScreenPro and ReGlobe trademarks and service marks and the entire contents of the Site are the property
											of
											Manak Waste Management Pvt Ltd and/or its affiliates or licensors, including the Third Parties, and are
											protected by international/Indian copyright and trademark laws, all rights reserved. Any violation of
											these
											restrictions may result in a copyright, trademark, or other intellectual property right infringement
											that
											may subject you to civil and/or criminal penalties.</p>
										<p>Other marks on the site not owned by Grest may be under license from the trademark owner thereof, in
											which
											case such license is for the exclusive benefit and use of Grest unless otherwise stated, or may be the
											property of their respective owners. You may not use any of the trademark name, logos, trademarks or
											brands,
											or trademarks or brands of others on the Site without Manak Waste Management Pvt Ltd&rsquo;s express
											permission.</p>
									</li>
								</ol>
			
								<ol start="4">
									<li><strong>Grest Services and Third Party Services and Sites</strong>
										<p>The information and materials provided in the Site and through the Services are intended for general
											reference only, and may not describe all of the terms, conditions, and exceptions applicable to
											Grest&rsquo;s Services. Grest presents information from Third Parties through the Grest Site and
											Services,
											including prices offered for your items, item descriptions, certain Third Party terms of service, and
											other
											information (&ldquo;Third Party Information&rdquo;). Grest cannot control, and is not responsible for
											the
											accuracy of any Third Party Information.</p>
										<p>You conduct your actual sales and other transactions directly with the Third Parties and, unless
											otherwise
											specifically and clearly indicated, not with Grest. Grest cannot control any aspect of your sales and
											transactions with Third Parties, and the Third Parties are solely responsible to you for all aspects of
											your
											sales and transactions with them.</p>
										<p>At times, the Grest Site may have links to websites hosted by the Third Parties and other entities (the
											&ldquo;Additional Sites&rdquo;), or such Additional Sites may have links to the Grest Site. These links
											are
											offered as a convenience and for informational purposes only, not as referrals or endorsements by Grest
											of
											the Additional Sites. The Additional Sites are maintained by their respective organizations, and those
											organizations are solely responsible for the content of their own websites. Grest does not verify nor
											make
											any warranty or representation about the content, accuracy, opinions expressed, warranties, products or
											services, intellectual property compliance, or links of such Additional Sites. You should read the
											privacy
											policies and Terms &amp; Conditions agreements of all Additional Sites.</p>
									</li>
								</ol>
			
								<ol start="5">
									<li><strong> Privacy and Passwords</strong>
										<p>Grest values and protects the privacy of your information. Please review the Grest privacy policy, as
											it
											contains important information relating to your use of the Site and Services. Some portions of the Site
											are
											protected and require a user identification code (&ldquo;User ID&rdquo;) and password for access.
											Unauthorized access or use of such portions of the Site is prohibited. You agree that you will notify
											Grest
											immediately if you believe that a third party has obtained your User ID or password, or if you believe
											that
											any unauthorized access or use may occur or has occurred. For your protection, if Grest believes that
											any
											unauthorized access may occur or has occurred, Grest may terminate access without prior notice to you.
											You
											also agree that Grest is permitted to act upon any instructions received such instructions as authorized
											by
											you.</p>
									</li>
								</ol>
			
								<ol start="6">
									<li><strong> Membership.</strong>
										<ol type="a">
											<li>Registration and Basic Membership Terms: Members are visitors to the site and or those using the
												Services
												that choose to register with Grest (&ldquo;Members&rdquo;). Once registered, an account is created for
												each
												Member (&ldquo;Account&rdquo;). If you choose to register as a Member, you represent and warrant to us
												that:
												<ol start="1">
													<li>you are of legal age to form a binding contract</li>
													<li>you will provide us with accurate, current and complete registration and contact information,
														and
														keep
														your information updated</li>
													<li>your registration and your use of the Services are not prohibited by law. We reserve the right
														to
														suspend or terminate your membership, or your access to the Site and or Services, in the event
														that
														you
														breach any of the Terms &amp; Conditions or other applicable Grest policies.</li>
			
												</ol>
											</li>
											<li>Password and Account Security: In connection with your Account, you will create a password and a
												user
												id. You are responsible for keeping your password and secure, and you are responsible for all actions
												taken using your password.</li>
											<li>Age: To create an Account or to otherwise use this ḍWebsite, you must be at least eighteen (18)
												years
												old
												or the age of majority in your state or province of residence, whichever is greater.</li>
										</ol>
									</li>
								</ol>
			
			
								<ol start="7">
									<li><strong> Inactive Accounts</strong></li>
									<p>Inactive Status: A Member&rsquo;s Account may be set to inactive if there is no activity associated with
										that Account for 180 days.</p>
									<li><strong> Warranty Exclusions and Limitations of Liability.</strong>
										<p>We warrant that the Services and Grest Property will conform substantially to the descriptions set
											forth on the Site. In the event of any breach of this warranty, the Customer&rsquo;s sole and exclusive
											remedy,
											and Grest&rsquo;s sole and exclusive liability, shall be (at Grest&rsquo;s option) to remedy the failure
											or to refund the monetary amount paid for the services by the Customer, if any. Except as set forth in
											the
											foregoing sentence, we make no representations or warranties of any kind regarding the Services or the
											Grest Property. We expressly disclaim any and all warranties, whether express or implied, including: all
											warranties of merchantability, fitness for a particular purpose, title, non-infringement, and any and
											all warranties arising from course of dealing and usage of trade; that the services and Grest property
											will
											meet your requirements, will always be available, accessible, uninterrupted, timely, secure or operate
											without error, as to the results that may be obtained from the operation, use or other exploitation of
											the
											services or Grest property, and as to the accuracy or reliability of any information obtained from the
											services or the Grest property. No advice or information, whether oral or written, obtained not
											expressly stated
											herein.
										</p>
										<p>Under no circumstances will you be entitled to recover from us any incidental, consequential, indirect,
											punitive or special damages (including damages for loss of business, loss of profits or loss of use),
											whether based on contract, tort (including negligence), or otherwise arising from or relating to the
											services or Grest property, even if Grest has been informed or should have known of the possibility of
											such
											damages. in any event, Grest&rsquo;s maximum aggregate liability for any and all damages arising from
											the
											services or the Grest property shall be a refund of the amount paid by you to us, if any.</p>
										<p>Some jurisdictions do not allow the limitation or exclusion of warranties or of liability, so some of
											the
											above limitations or exclusions may not apply to you.</p>
									</li>
								</ol>
			
								<ol start="9">
									<li><strong>Indemnity.</strong>
										<p>Customer agrees to indemnify and hold Grest, our affiliates, suppliers, licensors and partners, and the
											officers, directors, employees, agents and representatives of each of them harmless, including costs,
											liabilities and legal fees, from any claim or demand made by any third party due to or arising out of
											(i)
											your access to or use of Services, (ii) your violation of these Terms &amp; Conditions, or (iii) the
											infringement by you, or any third party using your account, of any intellectual property or other right
											of
											any person or entity. Grest reserves the right, at your expense, to assume the exclusive defense and
											control
											of any matter for which you are required to indemnify us and you agree to cooperate with our defense of
											these claims. You agree not to settle any matter without the prior written consent of Grest. We will use
											reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.</p>
									</li>
								</ol>
			
								<ol start="10">
									<li><strong> Applicable Law, Jurisdiction, Compliance</strong>
										<p>You and Grest agree that all matters arising from or relating to the use and operation of the Site
											and/or
											the Services will be governed by the substantive laws of Republic of India, without regard to its
											conflicts
											of laws principles. You agree that all claims you may have arising from or relating to the operation,
											use or
											other exploitation of the Site and/or the Services will be heard and resolved in the courts located in
											New
											Delhi. You consent to the personal jurisdiction of such courts over you, stipulate to the fairness and
											convenience of proceeding in such courts, and covenant not to assert any objection to proceeding in such
											courts.</p>
									</li>
								</ol>
			
								<ol start="11">
									<li><strong> Miscellaneous Provisions</strong>
										<p>No delay or omission by us in exercising any of our rights occurring upon any noncompliance or default
											by
											you with respect to any of these Terms &amp; Conditions will impair any such right or be construed to be
											a
											waiver thereof, and a waiver by us of any of the covenants, conditions or agreements to be performed by
											you
											will not be construed to be a waiver of any succeeding breach thereof or of any other covenant,
											condition or
											agreement hereof contained. As used in these Terms &amp; Conditions, &ldquo;including&rdquo; means
											&ldquo;including but not limited to.&rdquo; If any provision of these Terms &amp; Conditions is found by
											a
											court of competent jurisdiction to be invalid or unenforceable, then these Terms &amp; Conditions will
											remain in full force and effect and will be reformed to be valid and enforceable while reflecting the
											intent
											of the parties to the greatest extent permitted by law. Except as otherwise expressly provided herein,
											these
											Terms &amp; conditions set forth the entire agreement between you and Grest regarding its subject
											matter,
											and supersedes all prior promises, agreements or representations, whether written or oral, regarding
											such
											subject matter. You agree that the electronic text of these Terms &amp; Conditions constitutes writing
											and
											your assent to the terms and conditions hereof constitutes a &ldquo;signing&rdquo; for all purposes.</p>
									</li>
								</ol>
			
								<ol start="12">
									<li><strong> Information Collection, Use, and Sharing</strong>
										<p>By submitting any Grest contact form, you understand that you may be contacted by a Grest
											representative or
											a representative from the partner you&rsquo;ve chosen. You may be contacted via telephone, email, text,
											or
											prerecorded message regarding Grest programs, offers, events, announcements, and offers from
											Grest&rsquo;s
											third party marketing partners. If you respond to any such offer, your information will be subject to
											that
											third party&rsquo;s terms and conditions. By providing us your phone number, you grant Grest permission
											for
											the use of text messages, prerecorded voice or and/or automatic telephone dialing systems to contact you
											and/or deliver Grest related information, offers or announcements.</p>
										<p>You also agree that Grest may attempt to contact you via any telephone number you provide, even if it
											is a
											mobile telephone number which may result in charges to you. You can opt out from Grest email messaging
											at
											any time.</p>
										<p>You understand that agreeing to the run diagnostics on Grest app program will allow Grest access to
											your
											device, solely in relation to conducting the assessment of the quality parameters of your device. In no
											matter will your private information and data on the device will be accessed for any other purpose and
											that
											such information shall not be downloaded by the Company or used in any other manner.</p>
									</li>
								</ol>
							</div>
						</div>
					</div>
				</div>

				<div class="refund">
					<h3 class="mt-4">Refund Policy</h3>
					<div class="row">
						<div class=" col-10 mx-auto text-justify">
							<div class="content">
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>We offer you easy and streamlined replacement process</span></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>1. How do I file a Replacement request?</span></strong></p>
								<ol style='list-style-type: decimal;'>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>You can initiate the return making a call PHONE NO. or drop a mail info@Grest.in. Our support executive will raise a tick against your complaint.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>You can place a Replacement request within 7 days of order delivery. However, in case of Damaged/Missing Product, the Return request should be filed within 48 hours of delivery.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Replacement request will be reviewed by Grest.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>After approval, pickup of the product will be arranged through our courier partners.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>If our reverse pickup service is not available on your address, we will ask you to dispatch the product. The courier charges will be reimbursed by Grest up to Rs 150.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>After the product is received, it is verified against your claim and accordingly, Replacement is initiated. Please note that Replacement would depend upon the stock availability.</span></li>
								</ol>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>2. Under what conditions can I return/ replace my product?</span></strong></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>Returns/Replacement are accepted under the following cases -</span></p>
								<ol style='list-style-type: decimal;'>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Wrong Product &ndash; Wrong color/ size/ style</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Wrong item ordered/ delivered</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Defective Product - Manufacturing defect/ Non-functioning</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Damaged Product &ndash; Physical damage/ Tampered product or packaging</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Wrong Quantity &ndash; Missing Products/ Parts</span></li>
								</ol>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>3. Under what conditions Return / Replacement request will not be accepted?</span></strong></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>Return/ Replacement requests will not be accepted under following cases &ndash;</span></p>
								<ol style='list-style-type: decimal;'>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>If Products are Altered/ Used.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>If Product is returned without Original Packaging (price tags, labels &amp; accessories).</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>If Serial Number is tampered.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>For a Defective product that is covered under Grest&rsquo;s Warranty or Reported after 7 days of the Delivery.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>For Damaged/Missing product that is reported after 48 hours of the delivery.</span></li>
								</ol>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>4. What is the best time to place Return/ Replacement request?</span></strong></p>
								<ol style='list-style-type: decimal;'>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Return/Replace request of the Product(s) should be initiated within 7 days of Order Delivery for Wrong/ Unsatisfactory product.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>However, under the following conditions, Return Request should be filed within 48 hours of Delivery with the images of the parcel or product</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Damaged Product.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Empty Parcel.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Missing Item.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>To file a return/replacement request, please reach out to Grest&rsquo;s Customer Support.</span></li>
								</ol>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>5. When do you initiate Pickup for Returns?</span></strong></p>
								<ol style='list-style-type: decimal;'>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Once your request to replacement an order is approved, a pickup will be initiated. You will receive an email from us, with information on the packaging, return address and required documentation.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Please keep the product ready with all tags &amp; accessories. Kindly ensure proper packaging to avoid any damage during transit.</span></li>
								</ol>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:12px;font-family:Roboto;'>Please take care of the following points, while packing your product for Pickup:</span></strong></p>
								<ol style='list-style-type: decimal;'>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>The product should not be used/altered/ tampered.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Keep original price tag &amp; packing slip intact.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Mention Order Number on the box.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Do not seal the box.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Mention the Order Number/Delivery Address on the package, before handing over the packet to our Pickup executive.</span></li>
										<li><span style='font-family:Roboto;font-size:10.0pt;'>Keep the Courier Company&apos;s receipt for tracking purposes.</span></li>
								</ol>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:9px;font-family:Roboto;'>Please Note - Grest shall not be liable for any incidental defect/damage and mishandling etc.</span></strong></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>5. What do I do if my area does not have a reverse pick up service?</span></strong></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>If our reverse pickup service is not available at your address, we will ask you to dispatch the product. Return address will be notified to you in a separate email, along with the packaging instructions and required documents.</span></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>In case of Self-Shipment, Grest will reimburse your courier charges (up to Rs.150).</span></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>In case of Self-Shipment, Customer has to share the image of Courier Bill at our email address : info@Grest.in</span></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:12px;font-family:Roboto;'>Please take care of the following-</span></strong></p>
								<ol start='1' style='margin-bottom:0cm;' type='1'>
										<li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>Mention the Order number/Delivery Address on the package, before handing it over to the Courier Representative.</span></li>
										<li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>Send a scanned copy of the courier receipt to our address.</span></li>
										<li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>Track your Return Shipment on the Courier Company&apos;s Website.</span></li>
								</ol>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>7. How do I track the status of my Replacement request?</span></strong></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>Every request received at Grest is assigned a ticket number, for which an acknowledgment mail is sent to your registered email address. Please use your registered email ID and phone number for any further communication.</span></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>After receiving your Replacement Request, we will update you on the status i.e. Acceptance/Rejection of Reverse Pickup, Reshipment &amp; Replacement.</span></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>8. Can I track the status of Reverse Pickup?</span></strong></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>You will receive an email from us, within 24-48 Hours of Pickup, with the tracking details.</span></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>9. How to claim Return/ Replacement for products under Grest&rsquo;s Warranty?</span></strong></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>Please contact us at Grest.in/ Customer support.</span></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>10. Do I need to pay the courier company to send my product back?</span></strong></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>No, you don&apos;t need to pay anything to the courier representative if we arrange the pickup of your product. If you are using a courier service to ship your product back to our given address, you need to bear the courier cost at that time. However, the same will be reimbursed by us. The courier charges eligible for reimbursement are up to Rs.150.</span></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>11. Which documents do I need to attach for the return/ replacement process?&nbsp;</span></strong></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>Documents are required during the Reverse Pickup of any product, after placing a return/replacement request.</span></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>Reverse Pickup by Grest:</span></strong></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>Mention the Order Number on the package before handing over the packet to the Pickup executive. The receipt from the courier company must be kept as a proof for tracking purposes. Grest shall not be liable for any incidental defect/damage by the customer.</span></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>Self-Shipment:</span></strong></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>Mention the Order Number on the packet along with the Address (as mentioned in the email by us) before handing over the packet to the Courier Company. Share a scanned copy of the courier receipt with us, as a proof for dispatching the parcel, addressed to us. In case, you do not get a confirmation from us on receipt of the returned product, please track the shipment with the courier service provider.</span></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>12. How will I know that my Returned product has reached you?</span></strong></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>You will receive an email from us within 24-48 Hours of Pickup, along with the Tracking details. You can track the package on Courier Company&apos;s website.</span></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><strong><span style='font-size:13px;font-family:Roboto;'>How much time does it take to replace an order?</span></strong></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;,sans-serif;'><span style='font-size:13px;font-family:Roboto;'>We initiate the replacement within 2 working days of receiving the product at our center. The replacement may get delayed or declined if the product received by us is not as per your claim or in case of missing Order ID on the package.</span></p>
								<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;,sans-serif;'><span style='font-size:12px;line-height:107%;font-family:Roboto;'>&nbsp;</span></p>
							</div>
						</div>
					</div>
				</div>

				<div class="cancel">
					<h3 class="mt-4">Cancellation Policy</h3>
					<div class="row">
						<div class=" col-10 mx-auto text-justify">
							<div class="content">
								<p>Grest ensures that your order is safely delivered to you within the promised delivery timeline. However, if
									you have ordered a wrong product you may cancel the order through your Grest Account.</p>
								<p><strong>ORDER CANCELLATION BY GREST</strong></p>
								<p>Under some rare situations, Grest can also raise an order cancellation request.</p>
								<p><strong>These situations could be</strong></p>
								<ul>
									<li>Product out of stock</li>
									<li>Restrictions on the number of products you can order, as per Terms &amp; Conditions of any
										Offer/Discount</li>
									<li>Incorrect pricing or description of the product</li>
									<li>Payment fraud suspicion by our Credit &amp; Fraud Avoidance Department</li>
									<li>Incorrect or Incomplete Buyer's Address</li>
									<li>Non serviceability of Buyer&rsquo;s address by our courier partners.</li>
								</ul>
								<p><strong>Frequently Asked Questions</strong></p>
								 <p><strong>Ques: How can I cancel my order?</strong></p>
								<p>Ans: You can cancel your order if it is not shipped (COD Order Only). Please login to your Grest account
									for initiating the cancellation &amp; follow the given process:</p>
									&nbsp; &nbsp;	<p><strong>Sign-In &gt; My Account &gt; Order History &gt; Cancellation Request.</strong></p><br>
								<p><strong>Ques: Can I modify my order?</strong></p>
								<p>Ans: Yes, you can modify your order as long as it has not been shipped &amp; available with the same price.
									Kindly contact us at <a href="{{route('contact')}}" class="red-link">Grest.in/Contact</a> for any modification.</p><br>
								<p><strong>Ques: Can I change the quantity of my order?</strong></p>
								<p>Ans: You may request to modify your order before it has been shipped. You can track your order status at
									Grest.in/track order</p><br>
								<p><strong>Ques: COD Orders:</strong></p>
								<p>Ans: It is relatively simple to change the quantity of COD orders as the payment will be collected at the
									time of delivery.</p><br>
								<p><strong>Ques: Prepaid Orders:</strong></p>
								<p>Ans: If you wish to reduce the quantity of a prepaid order, contact us at <a href="{{route('contact')}}" class="red-link">Grest.in/Contact</a>.</p><br>
								<p><strong>Please Note:</strong></p>
								<ul>
									<li>If it is Prepaid Order, the amount will be refunded to you within 10 working days, in accordance with
										our Policy. A cancellation request cannot be made for Prepaid.</li>
								</ul>
							</div>
						</div>
					</div>
				</div>

				<div class="shipping">
					<h3 class="mt-4">Shipping Policy</h3>
					<div class="row">
						<div class=" col-10 mx-auto text-justify">
							<div class="content">
								<p>Grest promises 'No Anxiety Shipping' for all the products that you order. We ensure this by bringing
									together critical elements of shipment such as Packaging, Timely Delivery, Order Status Updates and Support
									from our trusted Logistics Partners.</p>
								<p>So once you have placed an order, rest assured as we will look after everything. Also, timely delivery of
									the order is our utmost priority however, actual delivery depends upon availability of the product, your
									shipping address etc. We have collaborated with top Courier and Logistics Partners to make sure that you
									receive your order on time. Each order is usually processed within 48 hours and we update you at every step,
									i.e. when the order is placed, processed, shipped and delivered. If you have any query related to shipping
									process, feel free to reach our customer support.</p>
								<h4 class="mt-4">Frequently Asked Questions</h4>
								<p><strong>Ques: How can I cancel my order?</strong></p>
								<p><strong>Ans: </strong>You can check the status of your order at Grest <a
										href='{{route('order.track')}}'>click here to track order</a>. We share timely updates about your
									order status via Email / SMS. The updates will apprise you of order confirmation / processing / shipping /
									delivery.</p><br>
								<p><strong>Ques: How long does it take to deliver the product after it has been dispatched?</strong></p>
								<p><strong>Ans: </strong>It usually takes between 3 to 5 Business days to deliver the order after it has been
									dispatched. We will notify you on your registered contact details via Email / SMS about the tracking number
									and will also share courier/delivery partner details, once the order has been dispatched.</p>
								<p>If the order is not confirmed by you over the phone, the same will be cancelled.</p><br>
								<p><strong>Ques: How much do you charge for COD Orders?</strong></p>
								<p><strong>Ans: </strong>The COD charges are mentioned on the product page. The final amount that you see
									while placing the order at Grest.in would include the product and COD charges.</p>
								<p>For Cash on Delivery (COD) orders, the amount to be paid is mentioned on the package. It is the same price
									that is displayed while placing the order. You are not required to pay any extra amount at the time of
									receiving the COD order.</p><br>
								<p><strong>Ques: My order is out for delivery, but has not reached?</strong></p>
								<p><strong>Ans: </strong>If the status is marked as &ldquo;OUT FOR DELIVERY&rdquo; and is not delivered to you
									in next 24 hours, kindly check with the courier company or contact us at <a href="{{route('contact')}}" class="red-link">Grest.in/Contact</a>. We will follow
									up with the courier partner until your order is delivered.</p><br>
								<p><strong>Ques: What do I do if my product is delivered to the wrong address?</strong></p>
								<p><strong>Ans: </strong>In case, you discover that the Courier Company has delivered your package to the
									wrong address, you should immediately contact us at <a href="{{route('contact')}}" class="red-link">Grest.in/Contact</a>. We will follow up with the courier
									partner and notify you at the earliest possible.</p><br>
								<p><strong>Ques: Why is my order not delivered within the expected delivery date?</strong></p>
								<p><strong>Ans: </strong>There could be a delay depending upon your shipping address, courier services and
									unfavorable climatic conditions. You can track your shipment at the courier company&rsquo;s website, using
									the tracking number sent to you on your registered Email/Contact number.</p>
								<p>If there's no update in shipment, please wait for 48 hours. Else, get in touch with the customer support
									team.</p><br>
								<p><strong>Ques: Can I schedule the delivery as per my availability?</strong></p>
								<p><strong>Ans: </strong>Schedule the day of delivery: If your order is not shipped, we can schedule the
									shipment of your order as per your convenience.</p>
								<p>Schedule the time of delivery: If your order is shipped, you can track the status at the courier
									partner&rsquo;s website and contact them for scheduling the time of delivery.</p><br>
								<p><strong>Ques: Can I change the Shipping Address?</strong></p>
								<p><strong>Ans: </strong>You may request for change of address as long as the order has not been handed over
									to our courier partner. You can track the status of your order from Grest 'My Account' section or <a
										href='{{route('order.track')}}'>click here to track order</a>.</p>
								<p>If the order has not reached the shipment stage, you can change your shipping address from 'My Account'
									section or contact us at <a href="{{route('contact')}}" class="red-link">Grest.in/Contact</a>. If your current order has already been shipped, you can still
									update the address in your Grest Address Book for future orders. To edit an existing address that is saved
									in your Grest Account, kindly visit the 'Address Book' page and click on 'Edit'. After you have made the
									required changes in the Address, click on 'Save'.</p>
							</div>
						</div>
					</div>
				</div> --}}

		</div>
		</section>
@endsection